server:
    port: 8081 # 서버 port 설정

spring:
    # application-xxx.yml로 만들면 xxx라는 profile이 생성되어 이를 통해 관리할 수 있다.
    #profiles:
    #    include: xxx

    # DB 설정
    datasource:
        #url: jdbc:h2:mem:testdb
        #driver-class-name: org.h2.Driver
        #username: sa
        #password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/cbkim?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234qwer!
        #initialization-mode: always

    sql:
        init:
            mode: always

    #h2 db 사용할 경우 추가 설정
    #h2는 메모리 DB로 테스트 할때 보통 사용함.
    #h2:
        #console:
            #enabled: true
            #path: /h2-console

    # JPA 설정
    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect # Name of the target database to operate on, auto-detected by default. Can be alternatively set using the “Database” enum.
        #database: H2 # Target database to operate on, auto-detected by default. Can be alternatively set using the “database-platform” property.
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true  # Initialize the schema on startup. # spring.jpa.hibernate.ddl-auto 속성을 사용할지 말지를 결정하는 옵션 default: false

        # OSIV
        # true일 경우 영속성 컨텍스트가 트랜잭션 범위를 넘어선 레이어까지 살아있다.
        # Api라면 클라이언트에게 응답될 때까지, View라면 View가 렌더링될 때까지 영속성컨텍스트가 살아있다.
        # defulat: true
        #open-in-view: true  # Register OpenEntityManagerInViewInterceptor. Binds a JPA EntityManager to the thread for the entire processing of the request.
        show-sql: false  # Enable logging of SQL statements.

        hibernate:
            # DDL(Data Definition Language): 스키마(Schema), 도메인(Domain), 테이블(Table), 뷰(View), 인덱스(Index)를 정의하거나 변경 또는 제거할 때 사용하는 언어
            # none, update, validata, create, create-drop
            # none: 초기화 동작을 하지 않는다.
            # update:  기존의 스키마를 유지하며 JPA에 의해 변경된 부분만 추가한다.
            # validate: 엔티티와 테이블이 정상적으로 매핑되어있는지만 검증한다.
            # create: 기존에 존재하는 스키마를 삭제하고 새로 생성한다.
            # create-drop: 스키마를 생성하고 애플리케이션이 종료될 때 삭제한다.
            ddl-auto: update  # DDL mode. This is actually a shortcut for the # hbm2ddl.auto 동일속성

        properties: # Additional native properties to set on the JPA provider.
            hibernate:
                #dialect: org.hibernate.dialect.H2Dialect # The classname of a Hibernate org.hibernate.dialect.Dialect which allows Hibernate to generate SQL optimized for a particular relational database.
                #dialect: org.hibernate.dialect.MySQL5Dialect
                # Yaml에서 특수키를 사용할 경우 '[]'의 형태를 가져야 함.
                '[format_sql]': true # Pretty print the SQL in the log and console.
                '[use_sql_comments]' : true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT를 표시합니다.



    #JWT Secret Key value
    jwt:
        secret: cndqja2021

    # mailSender 설정
    # 다른 메일을 사용할 경우 각 메일의 설정을 참고하여 설정하면 된다.
    mail:
        # google
        host: smtp.gmail.com
        port: 587
        username: cbkim@voimtech.com
        password: vptweztjidoohljh

        # naver
        #host: smtp.naver.com
        #port: 465
        #username: toonme@naver.com
        #password: qjadl0531A

        # 전송하기 위한 prop으로 ssl의 신뢰, 권한 등 사용허가
        properties:
            #'[mail.debug]': true
            '[mail.smtp.auth]': true
            '[mail.smtp.starttls.enable]': true
            # port: 465
            #'[mail.smtp.ssl.enable]': true
            #'[mail.smtp.ssl.trust]': '*'

    # SNS 계정으로 로그인 하기
    # 각 개발 사이트에 가입하여 어플리케이션을 생성한 다음 키를 받아야함.
    provider:
        google:
            client-id: 1053944983572-u13pt0nr6v3v9ou2qqqjseftt8gnuva2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

        naver:
            client-id: 9ECbMNhcRNPkP6yAahsN
            client-secret: w5pXiSaOud

        kakao:
            client-id: 0de9dba0c5b60a752511a4ccc4826ba1



#logging:
    #level:
        #'show-sql: true'와 동일하게 쿼리를 표시함.
        #'[org.hibernate.SQL]': debug
        #'[org.hibernate.type]': trace
